spring.application.name=ecommerce_order_manager
spring.datasource.url=jdbc:postgresql://localhost:5432/order_manager
spring.datasource.username=sudarshankumar
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false